version: '2'

services:

  publb:
    image: dockercloud/haproxy:1.6.7
    ports:
    - "443:443"
    - "1936:1936"
    links:
    - portal
    - kong
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    environment:
    - "STATS_AUTH=stats:stats"
    - "STATS_PORT=1936"
    restart: unless-stopped

  kongdb-data:
    image: postgres:9.6
    volumes:
    - "/var/lib/postgresql/data"
    command: "/bin/true"

  kong-database:
    image: postgres:9.6
    volumes_from:
    - "kongdb-data"
    environment:
    - "POSTGRES_USER=kong"
    - "POSTGRES_PASSWORD=kong"
    restart: unless-stopped

  kong:
    image: haufelexware/wicked.kong:0.12.5
    depends_on:
    - "kong-database"
    security_opt:
    - seccomp:unconfined
    expose:
    - "8000"
    environment:
    - "DATABASE=postgres"
    - "VIRTUAL_HOST=https://${PORTAL_NETWORK_APIHOST}:443"
    - "VIRTUAL_HOST_WEIGHT=100"
    - "EXCLUDE_PORTS=7946,8001,8443,8444"
    - "EXTRA_SETTINGS=http-request set-header X-Forwarded-Port %[dst_port]"
    - "SSL_CERT=${GATEWAY_PEM}"
    restart: unless-stopped

  portal-api-data-static:
    build: 
      context: static
    volumes:
    - "/var/portal-api/static"
    command: "/bin/true"

  portal-api-data-dynamic:
    image: haufelexware/wicked.portal-api:0.12.5-alpine
    volumes:
    - "/var/portal-api/dynamic"
    command: "/bin/true"

  portal-api:
    image: haufelexware/wicked.portal-api:0.12.5-alpine
    volumes_from:
    - "portal-api-data-static"
    - "portal-api-data-dynamic"
    restart: unless-stopped
    environment:
    - NODE_ENV
    - DEBUG
    - PORTAL_NETWORK_PORTALHOST
    - PORTAL_NETWORK_APIHOST
    - PORTAL_CONFIG_KEY
    - GIT_REPO
    - GIT_BRANCH
    - GIT_CREDENTIALS
    - GIT_REVISION

  portal:
    image: haufelexware/wicked.portal:0.12.5-alpine
    depends_on:
    - "portal-api"
    - "portal-redis"
    expose:
    - "3000"
    environment:
    - "VIRTUAL_HOST=https://${PORTAL_NETWORK_PORTALHOST}:443"
    - "VIRTUAL_HOST_WEIGHT=0"
    - "SSL_CERT=${PORTAL_PEM}"
    - "DEBUG"
    restart: unless-stopped

  portal-redis:
    image: redis:3.2-alpine
    expose:
    - "6379"

  portal-kong-adapter:
    image: haufelexware/wicked.portal-kong-adapter:0.12.5-alpine
    depends_on:
    - "portal-api"
    - "kong"
    restart: unless-stopped
    environment:
    - DEBUG

  portal-mailer:
    image: haufelexware/wicked.portal-mailer:0.12.5-alpine
    restart: unless-stopped
    depends_on:
    - "portal-api"
    environment:
    - DEBUG

  portal-chatbot:
    image: haufelexware/wicked.portal-chatbot:0.12.5-alpine
    restart: unless-stopped
    depends_on:
    - "portal-api"
    environment:
    - DEBUG
